on:
  push:
    branches:
      - master




jobs:
  build:
    runs-on: ubuntu-latest
 

    steps:
      - uses: actions/checkout@v3
  
      - name: "login to Docker hub"
        run: docker login --username ${{secrets.DOCKERUSERNAME}} --password ${{secrets.DOCKER_TOKENS}}

      - name: "building docker image"
        run: docker build -t ${{secrets.DOCKERUSERNAME}}/myimage .

      - name: "pushing to docker hub"
        run: docker push ${{secrets.DOCKERUSERNAME}}/myimage 


 